# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test
  demands:
  - agent.name -equals devops

steps:
- script: echo Hello, world in new Agent!

- script: |
    pwd
    dotnet --version
    dotnet tool install --global dotnet-sonarscanner
- script: |
    dotnet sonarscanner begin /k:"MiAppWebv3_minimal" /d:sonar.token="$(TOKEN_SONAR)"
  displayName: 'Sonarqube Begin'
- script: |
    dotnet build
  displayName: 'Build'
- script: |
    dotnet sonarscanner end /d:sonar.token="$(TOKEN_SONAR)"
  displayName: 'Sonarqube End'

