# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test
  demands:
  - agent.name -equals devops

steps:
- script: echo Hello, world in new Agent!

- script: |
    pwd
    dotnet --version
- script: |
    dotnet-sonarscanner begin /k:"MiAppWebv3_minimal" /d:sonar.host.url="http://192.168.156.20:5155/" /d:sonar.token="$(TOKEN_SONAR)"
  displayName: 'Sonarqube Begin'
- script: |
    dotnet build
  displayName: 'Build'
- script: |
    export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-1.el7_9.x86_64/jre/bin/java
    dotnet-sonarscanner end /d:sonar.token="$(TOKEN_SONAR)"
  displayName: 'Sonarqube End'

